# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "email_spec"
  s.version = "1.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Mabey", "Aaron Gibralter", "Mischa Fierer"]
  s.date = "2012-04-08"
  s.description = "Easily test email in rspec and cucumber"
  s.email = "ben@benmabey.com"
  s.extra_rdoc_files = [
    "History.txt",
    "MIT-LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "History.txt",
    "MIT-LICENSE.txt",
    "README.md",
    "Rakefile",
    "lib/email-spec.rb",
    "lib/email_spec.rb",
    "lib/email_spec/address_converter.rb",
    "lib/email_spec/background_processes.rb",
    "lib/email_spec/cucumber.rb",
    "lib/email_spec/deliveries.rb",
    "lib/email_spec/email_viewer.rb",
    "lib/email_spec/errors.rb",
    "lib/email_spec/helpers.rb",
    "lib/email_spec/mail_ext.rb",
    "lib/email_spec/matchers.rb",
    "lib/email_spec/test_observer.rb",
    "lib/generators/email_spec/steps/USAGE",
    "lib/generators/email_spec/steps/steps_generator.rb",
    "lib/generators/email_spec/steps/templates/email_steps.rb",
    "rails_generators/email_spec/email_spec_generator.rb",
    "rails_generators/email_spec/templates/email_steps.rb"
  ]
  s.homepage = "http://github.com/bmabey/email-spec/"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.16"
  s.summary = "Easily test email in rspec and cucumber"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<launchy>, ["~> 2.1"])
      s.add_runtime_dependency(%q<mail>, ["~> 2.2"])
      s.add_runtime_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<rake>, [">= 0.8.7"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rails>, ["= 3.0.7"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<cucumber-sinatra>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 2.0.1"])
      s.add_development_dependency(%q<delayed_job>, ["~> 2.0"])
      s.add_development_dependency(%q<mimetype-fu>, [">= 0"])
      s.add_development_dependency(%q<pony>, [">= 0"])
      s.add_development_dependency(%q<sinatra>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<database_cleaner>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
      s.add_development_dependency(%q<email_spec>, [">= 0"])
    else
      s.add_dependency(%q<launchy>, ["~> 2.1"])
      s.add_dependency(%q<mail>, ["~> 2.2"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<rake>, [">= 0.8.7"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rails>, ["= 3.0.7"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<cucumber-sinatra>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 2.0.1"])
      s.add_dependency(%q<delayed_job>, ["~> 2.0"])
      s.add_dependency(%q<mimetype-fu>, [">= 0"])
      s.add_dependency(%q<pony>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<database_cleaner>, [">= 0"])
      s.add_dependency(%q<test-unit>, [">= 0"])
      s.add_dependency(%q<email_spec>, [">= 0"])
    end
  else
    s.add_dependency(%q<launchy>, ["~> 2.1"])
    s.add_dependency(%q<mail>, ["~> 2.2"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<rake>, [">= 0.8.7"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rails>, ["= 3.0.7"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<cucumber-sinatra>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 2.0.1"])
    s.add_dependency(%q<delayed_job>, ["~> 2.0"])
    s.add_dependency(%q<mimetype-fu>, [">= 0"])
    s.add_dependency(%q<pony>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<database_cleaner>, [">= 0"])
    s.add_dependency(%q<test-unit>, [">= 0"])
    s.add_dependency(%q<email_spec>, [">= 0"])
  end
end

